### ISSUE TITLE
How to invoke help when no args passed

### ISSUE THREAD

**Issue by innovia** [stedmeister/easyargs#14]
Hi

I would like to show the help for the main class when no args are passed

can you please help?

**Comment by stedmeister** [comment]
Testing this out.  With the following code:

    import easyargs
  
    @easyargs
    class Foo(object):
        """This is some help"""
        def foo(self):
            pass

        def bar(self, gh):
            pass

    Foo()

On the command line, with no args, I get:

    $ python myfile.py 
    usage: myfile.py [-h] {bar,foo} ... 
    myfile.py: error: too few arguments

But if I supply `-h` I get more:

    $ python myfile.py -h
    usage: myfile.py [-h] {bar,foo} ...

    This is some help

    positional arguments:
      {bar,foo}   sub-command help
        bar
        foo

    optional arguments:
      -h, --help  show this help message and exit

I'm guessing you'd like to have the second text printed when there are no arguments?

If this is possible with argparse, then something can probably be done.

**Comment by innovia** [comment]
I would like to trigger -h if no args provided so the full hep is shown if no args are given

**Comment by innovia** [comment]
```python
import argparse
import sys

parser=argparse.ArgumentParser()
parser.add_argument('foo', nargs='+')
if len(sys.argv)==1:
    parser.print_help()
    sys.exit(1)
args=parser.parse_args()
```

can you help me plug it into the script?

**Comment by stedmeister** [comment]
You can edit `sys.argv` before calling my class.  Using my example code above, something like:

    if len(sys.argv)==1:
        sys.argv.append('-h')
    Foo()

**Comment by innovia** [comment]
Great! thanks alot
