### ISSUE TITLE
Multiline doc strings are parsed into help strings with connected words

### ISSUE THREAD

**Issue by Sveder** [stedmeister/easyargs#16]
When using easyargs on a function with a multi-line docs string removes the \n between the lines thus connecting the words at end and start of line into one word.

Example:
```
@easyargs
def moo():
    """
    Some super long explanation that
    takes more than one line.
    """
```

I'd expect the help string to be - "Some super long explanation that **takes more** than one line.", instead it is "Some super long explanation **thattakes** more than one line.".

I'm not sure what the best fix is, but I think that in:
https://github.com/stedmeister/easyargs/blob/master/easyargs/parsers.py#L28

you can add the \n removed by the .splitlines() back in the
```
            main_text += line
```
line by making it:
```
            main_text += line + '\n'
```
.

**Comment by Sveder** [comment]
@stedmeister Should I open a PR?

**Comment by stedmeister** [comment]
Yes please. I think a better fix would be to add a space instead of a new line: 

    main_line += line + ' '

**Comment by Sveder** [comment]
Fixed, thanks @stedmeister :)
