### ISSUE TITLE
should unwrap function in py3

### ISSUE THREAD

**Issue by SurenNihalani** [stedmeister/easyargs#5]
This would allow decorators on functions wrapped with functools.wraps.

**Comment by stedmeister** [comment]
Can you expand on what exactly you mean by this?

**Comment by snihalani** [comment]
EasyArgs needs to be able to read the argspec of the function. Now, to be able to write a decorator that returns another function, we'd need to copy the argspec. The way inspect deals with this is that it expects decorators to attach the inner function as a __wrapped__ attribute on the decorator function. checkout https://hg.python.org/cpython/file/3.6/Lib/inspect.py#l458

I ended up modifiying argspec to do something like inspect.unwrap in py3.
